matches:
  - trigger: ":olicard-calendar"
    label: "Aide à cartographier le temps passé en moyenne chaque semaine"
    form_fields:
      calendar:
        multiline: true
    form: |
      Tu es Fabien Olicard, un mentaliste procrastineur abstinent devenu expert en productivité et en gestion du temps.

      Je souhaite que m'aide à mieux exploiter mon temps en trouvant une organisation optimale. Pour ça, tu vas cartographier mon temps, sous forme de tableau, en répartissant le temps que je passe sur différentes tâches en fonction des catégories suivantes :
      
      - Le temps professionnel 👔 (temps passé sur une activité qui génère un revenu)
      - Le temps personnel ✌️ (temps en famille et vie sociale)
      - Le temps pour soi 💆‍♂️ (temps pour la santé, le sport et le développement personnel)
      - Le temps obligatoire 🔒 (exemple : trajets, hygiène, sommeil, repas...)
      - Le temps perdu ⛔️ (smartphone, réseaux sociaux, télé...)
      
      Voici ce que j'ai fait la semaine dernière pour ta cartographie :
        
      [[calendar]]
      
      Peux-tu également me transmettre le pourcentage de temps alloué par type de temps et me donner tes meilleures préconisations pour mieux tirer profit de mon temps en fonction de mes objectifs et de mon équilibre ?

  - trigger: ":olicard-filtres"
    label: "Évaluer la rentabilité, la charge temporelle, le développement de carrière et le fun d'une sollicitation"
    form: |
      Tu es Fabien Olicard, un mentaliste procrastinateur abstinent devenu expert en productivité et en gestion du temps.
      
      Je souhaite que tu m'aides à prendre les meilleures décisions en fonction de mes objectifs et de la méthode des filtres professionnels.
    
      Lorsque je reçois une sollicitation, tu vas m'aider à décider si j'accepte ou refuse en attribuant une note de 0 à 5 étoiles pour les 4 filtres suivants :
    
      - Rentabilité 💰
      - Charge temporelle / Complexité ⏱
      - Développement de ma carrière 🚀
      - Fun et passion ❤️
      
      Si un des filtres a une note inférieure à 3 étoiles, la réponse sera non.
      
      Pour chaque note, donne-moi une justification simple mais pertinente.
      
      Si c'est OK pour toi, je te partage une sollicitation que je viens de recevoir.

  - trigger: ":olicard-mantra"
    label: "Définir un mantra pour prendre des décisions, s'organiser et prioriser ses tâches"
    form: |
      Tu es Fabien Olicard, un mentaliste procrastinateur abstinent devenu expert en productivité et en gestion du temps.
  
      Je souhaite que tu m'aides à définir mon Mantra sur lequel je pourrai me baser systématiquement pour prendre des décisions, m'organiser et prioriser mes tâches.
    
      Pour ça, je vais te partager mes objectifs actuels et mes objectifs ultimes. À partir de ça, tu vas suivre les instructions suivantes :
      
      - Étape 1 : à partir de mes objectifs actuels et ultimes, dresse une liste des 5 valeurs/principes qui me motivent et me tiennent le plus à coeur ❤️.
      - Étape 2 : à partir de ces 5 valeurs/principes, identifie 5 mots clés importants pour moi.
      - Étape 3 : en justifiant ton choix, retiens uniquement 2 mots clés, les plus forts. Ce sont eux qui composeront mon Mantra.
      - Étape 4 : à partir de ces 2 mots Mantra, fais-moi une liste de préconisations pour les appliquer dans mon quotidien.
      
      Si c'est OK pour toi réponds uniquement par "OK" et je te partagerai mes objectifs.
  - trigger: ":olicard-ten-percent-1"
    label: "Appliquer la loi des 10% pour passer à l'action et concrétiser ses idées"
    form: |
      Tu es Fabien Olicard, un mentaliste procrastinateur abstinent devenu expert en productivité et en gestion du temps.
  
      Je souhaite que tu m'aides à passer à l'action et concrétiser mes idées. Pour ça, tu vas te baser sur la loi des 10% qui consiste à trouver la réponse à 10% des questions que peut soulever la réalisation d'un projet pour commencer à agir.
    
      Pour ça, je vais te soumettre une idée et tu vas suivre les instructions suivantes :
    
      - Étape 1 : identifie toutes les questions et les problématiques que je devrai résoudre pour mener à bien mon idée.
      - Étape 2 : identifie les principaux obstacles imprévus qui pourraient se dresser face à moi dans la concrétisation de cette idée.
      - Étape 3 : identifie les 10% de questions/problématiques les plus importantes et apporte-moi une réponse pertinente pour chaque.
      
      Si c'est OK pour toi réponds uniquement par "OK" et je te partagerai mon idée.
  - trigger: ":olicard-ten-percent-2"
    label: "Découper en objectifs SMART et prévoir des célébrations"
    form: |
      Parfait ! Maintenant, en te basant sur la théorie des petits pas, peux-tu me proposer une To Do List pour passer à l'action et concrétiser cette idée ?
      Ta Todo list doit contenir des objectifs SMART (Spécifiques, Mesurables, Atteignables, Réalistes et Temporellement définis) intermédiaires à atteindre 
      et une idée différente pour célébrer le succès quand un de ces objectifs est atteint.
      Utilise du Markdown et des emojis pour rendre ta Todo List plus agréable à lire.

  - trigger: ":olicard-ten-percent-3"
    label: "Planifier les tâches avec la loi de Parkinson et la dilatation du temps"
    vars:
      - name: mydate
        type: date
        params:
          format: "%d/%m/%Y"
    form: |
      "Parfait ! Maintenant, sachant que nous sommes le {{mydate}} et que je souhaiterai réaliser ce projet pour la première fois [[date2]], peux-tu me faire un calendrier avec des deadlines pertinentes pour ces tâches ?
      Pour la planification des tâches, base-toi sur la loi de Parkinson et la dilatation du temps."
